version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Nano.Example.sln && dotnet publish ./Nano.Example.sln -c Release -o ./obj/Docker/publish"