version: '3.0'

services:
  nanocore.example:
    image: nanocore.example
    build:
      context: ./../NanoCore.Example
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - mysql
      - rabbitmq
      - elasticsearch
      - kibana
      - google

  mysql:
    image: mysql/mysql-server
    ports:
      - 3306:3306
    environment:
        MYSQL_USER: "myUser"
        MYSQL_PASSWORD: "myPassword"
        MYSQL_ROOT_PASSWORD: "myPassword"
        MYSQL_DATABASE: "examplesDb"

  rabbitmq: 
    image: rabbitmq:alpine
    ports:
      - 5671:5671
      - 5672:5672
    environment: 
      RABBITMQ_DEFAULT_USER: "myUser"
      RABBITMQ_DEFAULT_PASS: "myPassword"
      RABBITMQ_DEFAULT_VHOST: "/"
  
  elasticsearch:
    image: elasticsearch:alpine

  kibana:
    image: kibana
    ports:
      - 5601:5601

  google:
    image: niallmccullagh/docker-google-cloud-emulators:latest
    container_name: gcp-pubsub-emulator
    ports:
      - 8538:8538
    command: /bin/bash -c "gcloud config set project emulator && gcloud beta emulators pubsub start --data-dir /mnt/data/pubsub --host-port 0.0.0.0:8538"

